### ISSUE TITLE
[상품] QR코드 스캔 기능 및 UI 추가

### ISSUE THREAD

**Issue by danielchoi1115** [it-e-7/hyunprise#8]
## 💁 설명
- QR 코드 스캔 기능 페이지

## 📑 체크리스트

- [x] 툴바
  - [x] 뒤로가기
- [x] 스캔 화면 띄우기 
- [x] QR 코드 스캔
  - [x] 데이터 형식에 맞게 저장
  - [x] 쿠폰 발견 페이지 이동   
- [x] UI
  - [x] ConstraintLayout 적용
  - [x] 컴포넌트 배치
  - [x] 아이콘 적용
  - [ ] 폰트, 사이즈, 스타일 적용

## 🚧 주의 사항

**Comment by seoy316** [comment]
구현 완료
