### ISSUE TITLE
[메인] 홈 배너, 네비게이션 바, Drawer UI 추가

### ISSUE THREAD

**Issue by danielchoi1115** [it-e-7/hyunprise#9]
## 💁 설명
- 홈 배너 UI
- 네비게이션 바 UI
- Drawer UI

## 📑 체크리스트

- [x] 홈 배너
  - [x] 상단 고객 바코드 띄우기
  - [x] 배너 띄우기
  - [x] 하단 버튼 넣기 (기능X)
- [x] 네비게이션 바
  - [x] 메인 페이지, QR 스캔 페이지, 포인트몰 페이지에 적용
  - [x] 버튼 아이콘 적용
- [x] Drawer
  - [x] 메인 페이지 우측 상단에 버튼 추가
  - [x] 포인트, 바코드 등 페이지 아이콘 추가
  - [x] 영수증/쿠폰, 포인트샵만 기능추가
- [x] UI 공통사항
  - [x] ConstraintLayout 적용
  - [x] 아이콘 적용
  - [x] 폰트, 사이즈, 스타일 적용

## 🚧 주의 사항

**Comment by seoy316** [comment]
완료

**Comment by seoy316** [comment]
완료
